### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by ziggi** [J0shES/samp#24]
What the plans about this project?
Are you planning to keep compatibility with 0.3.7?
Why you are using 0.2.5 version as base and not 0.2X?
Where is the other sources (.saa packer, launcher, etc)?

**Comment by ziggi** [comment]
Also I suggest to [detach](https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/#commit-was-made-in-a-fork) the fork from the jovazxc project.

**Comment by J0shES** [comment]
- I might plan to keep compatibility with 0.3.7 but that is far off from now.
- Plans? None really, just going as I go.
- I could only find the 0.2.5 version, if you know where the 0.2x version could you direct me to it?
- I have the .saa builder on my HDD so I'll push that to the repo later, about the launcher there was no code leaked for the launcher (afaik) only server, client, saa2, 1000p key builder and the install.nsi code.

**Comment by ziggi** [comment]
https://mega.nz/#!4QwC1BIT!aImf8DTwFg6-6vhcZMD4oRKxz_QGke7zwEoxia8If7o

**Comment by J0shES** [comment]
Thanks, I'll look into using this instead of the current 0.2.5 on the repo.

**Comment by J0shES** [comment]
Well, I've got the 0.2x client and server running and compiling fine. Thanks for the link to 0.2x. 👍

**Comment by IstuntmanI** [comment]
I wanted to ask about the plans too.

I think that SA-MP should really come open-sourced. The beta testers could be the ones who can approve pull requests or only Kalcor (but I guess that he is way too inactive everywhere), so it won't transform in a Garry's Mod like MTA did. I don't think that the community would start spreading too much. The benefits would be way bigger than the disadvantages. If servers would use their own modifications they could lose players or better just use MTA as it already has everything.

By the way, I like that you are fixing and adding things that SA-MP should have had since few years ago but doesn't. Nice work. But I think that this isn't helping anyone, as long as Kalcor isn't peeking around at your changes and do them too. For me, it is just interesting to watch possible internal fixes to ancient bugs and really wanted additions.

I have only one request for now, just for the sake of curiosity, as I won't use any unofficial modification of SA-MP: could you try making this suggestion ?: http://forum.sa-mp.com/showpost.php?p=3668887&postcount=2559 -> the one before those first lines. It is a callback that would really help me (and probably others too, as I saw others replying to this suggestion of mine too). I really wonder how hard would be adding something like that, I requested that thing for first time in 2013 IIRC and I still need it A LOT. After all, this is just another thing that SA-MP should really have, as it is affecting the player position client-sided. Also, some callback when teleporting when exiting from vehicles when there's no space for exiting too, probably the same callback with a ```type``` parameter, 0 for underground and 1 for exiting vehicle.
I should probably create an issue for this suggestion, but I don't think there's any need for an issue about this. If you want to try to make this, fine.

I hate the way SA-MP is developing and the way the team is communicating with us (they don't do at all). Open sourcing on GitHub would be the best solution to both things, as we would have some kind of "automatic communication", being able to see the development when we want.

**Comment by J0shES** [comment]
I've added the hook code to be able to detect when the  game teleports the player. It currently crashes though due to my botched X,Y,Z getting. (https://github.com/J0shES/samp/commit/767c66355c7d5a2898eaa9aa1aac5fd994b947dd)
